---
title: "Alternative Simple Interaction Effects for Research Question 3"
author: "Pooya Razavi"
date: "2022-10-28"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(lmerTest)
library(sjPlot)
library(sjmisc)
library(emmeans)
library(MetBrewer)


df <- read.csv("Perc_AngExpress_longish_scored.csv")


#a dataframe with only the relevant variables, and predictors as factors
df2 <- df %>% 
            select(duration, response_id, scenario, harm_target, prot_gender, anger_express, 
                   communalism, steadfastness, wisdom, obstinacy) %>% 
            mutate_if(sapply(., is.character), as.factor)          

levels(df2$harm_target) <- c("Other", "Self")
levels(df2$prot_gender) <- c("Female", "Male")
levels(df2$anger_express) <- c("No", "Yes")

knitr::opts_chunk$set(echo = TRUE, emm_options(pbkrtest.limit = 4000))
```

# Communalism

## The models

### Omnibus

```{r communal-model0}
#setting the contrasts
    contrasts(df2$harm_target) <- contr.sum
    contrasts(df2$prot_gender) <- contr.sum
    contrasts(df2$anger_express) <- contr.sum

#omnibus model
    communalism_m1 <- lmer(communalism ~ harm_target * prot_gender * anger_express + (1 | response_id),
                                 data = df2)
    anova(communalism_m1)
```

### Simple interaction effect

```{r communal-models3}
#interaction
  communalism_rq3_model <- df2 %>% 
                            dplyr::filter(anger_express == "Yes") %>% 
                                lmer(communalism ~ harm_target * prot_gender + (1 | response_id),
                                                           data = .)
  anova(communalism_rq3_model, type = "III") %>% knitr::kable(format = "pipe")
#simple interaction effects
  emmeans(communalism_rq3_model, pairwise ~  prot_gender | harm_target)

```

## Visualizations

```{r}
#using emmeans

    emmip(communalism_rq3_model, ~ prot_gender * harm_target)
    
#using sjplots
    plot_model(communalism_rq3_model, type = "pred", terms = c("harm_target", "prot_gender"),
                    title = "Outcome: Communalism",
                     axis.title = c("Target of Harm", "Rating of Communalism"),
                    legend.title = "Protagonist's Gender",
                    axis.lim = c(1,5)) +
                    theme_bw()

#using ggplot
      descripts <- psych::describeBy(df2$communalism, 
                         group = list(df2$anger_express, df2$harm_target, df2$prot_gender), mat = TRUE)   %>% 
                        select(group1, group2, group3, mean, se) %>% 
                        transmute(Expression = group1,
                                  Target = group2,
                                  Gender = group3,
                                  mean, se) %>% 
                        filter(Expression == "Yes")

      
     #interaction plot - dot-whiskers and line plot
    com_rq3 <- ggplot(
                descripts,
                aes(x = Gender, color = Target, group = Target, y = mean,
                    ymin = mean-se, ymax = mean+se)) + 
                geom_line(position = position_dodge(0.1)) +
                geom_errorbar(position = position_dodge(0.1), width = 0.12) +
                geom_point(aes(color = Target), position = position_dodge(0.1), size = .8) +
                ylim(1, 5) +
                theme_bw() + 
                ggtitle("Communalism") +
                labs(y="Rating of Protagonist's Communalism", x = "Protagonist's Gender", color = "Target of Harm") +
                theme(plot.title = element_text(hjust = 0.5), text = element_text(size = 10)) + 
                      scale_color_manual(values=met.brewer("Nizami", 2, direction=-1))      

    com_rq3
      #ggsave(plot = com_rq3, width = 5, height = 5, dpi = 600, filename = "communalism_rq3.png")    

```

# Steadfastness

### Omnibus

```{r steadfast-model0}

    steadfastness_m1 <- lmer(steadfastness ~ harm_target * prot_gender * anger_express + (1 | response_id),
                                 data = df2)
    anova(steadfastness_m1) 
```

### Simple interaction effect

```{r steadfast-models3}
#interaction
  steadfast_rq3_model <- df2 %>% 
                            dplyr::filter(anger_express == "Yes") %>% 
                                lmer(steadfastness ~ harm_target * prot_gender + (1 | response_id),
                                                           data = .)
  anova(steadfast_rq3_model, type = "III") %>% knitr::kable(format = "pipe")
#simple interaction effects
  emmeans(steadfast_rq3_model, pairwise ~  prot_gender | harm_target)
  
  
```


## Visualization

```{r steadfast-visuals-rq3, fig.align='center', fig.width=5}
    #getting mean and se for the graph
      descripts <- psych::describeBy(df2$steadfastness, 
                         group = list(df2$anger_express, df2$harm_target, df2$prot_gender), mat = TRUE)   %>% 
                        select(group1, group2, group3, mean, se) %>% 
                        transmute(Expression = group1,
                                  Target = group2,
                                  Gender = group3,
                                  mean, se) %>% 
                        filter(Expression == "Yes")

      
     #interaction plot - dot-whiskers and line plot
  stead_rq3 <- ggplot(
                descripts,
                aes(x = Gender, color = Target, group = Target, y = mean,
                    ymin = mean-se, ymax = mean+se)) + 
                geom_line(position = position_dodge(0.1)) +
                geom_errorbar(position = position_dodge(0.1), width = 0.12) +
                geom_point(aes(color = Target), position = position_dodge(0.1), size = .8) +
                ylim(1, 5) +
                theme_bw() + 
                ggtitle("Steadfastness") +
                labs(y="Rating of Protagonist's Communalism", x = "Protagonist's Gender", color = "Target of Harm") +
                theme(plot.title = element_text(hjust = 0.5), text = element_text(size = 10)) + 
                      scale_color_manual(values=met.brewer("Nizami", 2, direction=-1))      

    stead_rq3
      #ggsave(plot = stead_rq3, width = 5, height = 5, dpi = 300, filename = "steadfastness_rq3.png")
    
    
```

# Wisdom

## The models

### Omnibus

```{r wisd-model0}
    wisdom_m1 <- lmer(wisdom ~ harm_target * prot_gender * anger_express + (1 | response_id),
                                 data = df2)
    anova(wisdom_m1)
```

### Simple interaction effect

```{r wisd-models3}

#interaction
  wisdom_rq3_model <- df2 %>% 
                            dplyr::filter(anger_express == "Yes") %>% 
                                lmer(wisdom ~ harm_target * prot_gender + (1 | response_id),
                                                           data = .)
  anova(wisdom_rq3_model, type = "III") %>% knitr::kable(format = "pipe")
#simple interaction effects
  emmeans(wisdom_rq3_model, pairwise ~  prot_gender | harm_target)
  
```

## Visualization

### Research question 3

```{r wisd-visuals-rq3, fig.align='center', fig.width=5}
      #getting mean and se for the graph
      descripts <- psych::describeBy(df2$wisdom, 
                         group = list(df2$anger_express, df2$harm_target, df2$prot_gender), mat = TRUE)   %>% 
                        select(group1, group2, group3, mean, se) %>% 
                        transmute(Expression = group1,
                                  Target = group2,
                                  Gender = group3,
                                  mean, se) %>% 
                        filter(Expression == "Yes")

      
     #interaction plot - dot-whiskers and line plot
  wis_rq3 <- ggplot(
                descripts,
                aes(x = Gender, color = Target, group = Target, y = mean,
                    ymin = mean-se, ymax = mean+se)) + 
                geom_line(position = position_dodge(0.1)) +
                geom_errorbar(position = position_dodge(0.1), width = 0.12) +
                geom_point(aes(color = Target), position = position_dodge(0.1), size = .8) +
                ylim(1, 5) +
                theme_bw() + 
                ggtitle("Wisdom") +
                labs(y="Rating of Protagonist's Wisdom", x = "Protagonist's Gender", color = "Target of Harm") +
                theme(plot.title = element_text(hjust = 0.5), text = element_text(size = 10)) + 
                      scale_color_manual(values=met.brewer("Nizami", 2, direction=-1))      

    wis_rq3
      #ggsave(plot = wis_rq3, width = 5, height = 5, dpi = 300, filename = "wisdom_rq3.png")
    

```

# Obstinacy

## The models

### Omnibus

```{r obstin-model0}

    obstinacy_m1 <- lmer(obstinacy ~ harm_target * prot_gender * anger_express + (1 | response_id),
                                 data = df2)
    anova(obstinacy_m1)

```


# interaction
```{r}

  obstinacy_rq3_model <- df2 %>% 
                            dplyr::filter(anger_express == "Yes") %>% 
                                lmer(obstinacy ~ harm_target * prot_gender + (1 | response_id),
                                                           data = .)
  anova(obstinacy_rq3_model, type = "III") %>% knitr::kable(format = "pipe")

  #simple interaction effects
    emmeans(obstinacy_rq3_model, pairwise ~  prot_gender | harm_target)
    
```

## Visualization

```{r obstin-visuals-rq3, fig.align='center', fig.width=5}

      #getting mean and se for the graph
      descripts <- psych::describeBy(df2$obstinacy, 
                         group = list(df2$anger_express, df2$harm_target, df2$prot_gender), mat = TRUE)   %>% 
                        select(group1, group2, group3, mean, se) %>% 
                        transmute(Expression = group1,
                                  Target = group2,
                                  Gender = group3,
                                  mean, se) %>% 
                        filter(Expression == "Yes")

      
     #interaction plot - dot-whiskers and line plot
  obst_rq3 <- ggplot(
                descripts,
                aes(x = Gender, color = Target, group = Target, y = mean,
                    ymin = mean-se, ymax = mean+se)) + 
                geom_line(position = position_dodge(0.1)) +
                geom_errorbar(position = position_dodge(0.1), width = 0.12) +
                geom_point(aes(color = Target), position = position_dodge(0.1), size = .8) +
                ylim(1, 5) +
                theme_bw() + 
                ggtitle("Obstinacy") +
                labs(y="Rating of Protagonist's Obstinacy", x = "Protagonist's Gender", color = "Target of Harm") +
                theme(plot.title = element_text(hjust = 0.5), text = element_text(size = 10)) + 
                      scale_color_manual(values=met.brewer("Nizami", 2, direction=-1))      

    obst_rq3
      #ggsave(plot = obst_rq3, width = 5, height = 5, dpi = 300, filename = "obstinacy_rq3.png")
    

```



